# Generated by Django 4.0.5 on 2022-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_paytmorder_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
