# Generated by Django 4.0.5 on 2022-06-19 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantspecificinfo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmorder',
            name='user_email',
        ),
        migrations.AddField(
            model_name='paytmorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
