# Generated by Django 4.0.5 on 2022-06-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_paytmorderdetails_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmorder',
            name='product_name',
        ),
    ]
