# Generated by Django 4.0.5 on 2022-06-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_remove_paytmorder_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmorderdetails',
            name='item_id',
        ),
    ]
