# Generated by Django 4.0.5 on 2022-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_user_referral_code_user_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmorder',
            name='order_mode',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
