# Generated by Django 4.0.5 on 2022-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_user_reference_code_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
