# Generated by Django 4.0.5 on 2022-06-12 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_paytmorder_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='addressOnMap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='RestaurantSpecificInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_phone', models.CharField(max_length=15)),
                ('owner_phone', models.CharField(max_length=15)),
                ('adhar_card', models.FileField(upload_to='restaurant-credentials/')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('pan_card', models.FileField(upload_to='restaurant-credentials/')),
                ('FSSAI_certificate', models.FileField(upload_to='restaurant-credentials/')),
                ('addressString', models.CharField(max_length=200)),
                ('tag_line', models.CharField(max_length=255)),
                ('media', models.FileField(upload_to='restaurant/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.college')),
            ],
        ),
    ]
