# Generated by Django 4.0.5 on 2022-06-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_restaurant_restaurant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
