# Generated by Django 4.0.5 on 2022-06-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmorder',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
