# Generated by Django 4.0.5 on 2022-06-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitems_explainer_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=25)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='media',
            field=models.FileField(upload_to='restaurant/'),
        ),
    ]
