# Generated by Django 4.0.5 on 2022-06-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_paytmorder_alter_restaurant_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmorder',
            name='order_schedule_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paytmorder',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaytmOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_serving', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.paytmorder')),
            ],
        ),
    ]
