# Generated by Django 4.0.5 on 2022-06-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_paytmorder_order_schedule_date_paytmorder_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmorder',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
