# Generated by Django 4.0.5 on 2022-06-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_addressonmap_restaurantspecificinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantspecificinfo',
            name='owner_name',
        ),
    ]
