# Generated by Django 4.0.5 on 2022-06-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_paytmorder_user_email_paytmorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmorderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='restaurants.paytmorder'),
        ),
    ]
