# Generated by Django 4.0.5 on 2022-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_remove_paytmorderdetails_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
