# Generated by Django 4.0.5 on 2022-06-24 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_email',
            field=models.EmailField(default='q@r.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_phone',
            field=models.CharField(default=1234567890, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Exact 10 digits allowed.", regex='^[6-9]\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantspecificinfo',
            name='restaurant_email',
            field=models.EmailField(default='q@r.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantspecificinfo',
            name='restaurant_phone',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Exact 10 digits allowed.", regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Exact 10 digits allowed.", regex='^[6-9]\\d{9}$')]),
        ),
    ]
