# Generated by Django 4.0.5 on 2022-06-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='food_category',
            field=models.IntegerField(),
        ),
    ]
